# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3


default: &default
  adapter: postgresql
  host: ec2-50-16-229-89.compute-1.amazonaws.com
  database: d8397j4kkiuql1
  username: rwbxhxpennbtqc
  password: fq3490orusx_5aUPbwexZZkB5R
  url: postgres://rwbxhxpennbtqc:fq3490orusx_5aUPbwexZZkB5R@ec2-50-16-229-89.compute-1.amazonaws.com:5432/d8397j4kkiuql1
  port: 5432